### ISSUE TITLE
Configure saga storage on MS SQL Server with Always Encrypted

### ISSUE THREAD

**Issue by gogux** [rebus-org/Rebus.SqlServer#67]
If I try to start an Azure WebJob that uses Rebus to communicate with a message queue using SqlServer storage for the sagas it throws the following exception (this is the innermost exception):

```
Keyword not supported: 'column encryption setting'.

   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Rebus.SqlServer.DbConnectionProvider.CreateSqlConnectionSuppressingAPossibleAmbientTransaction()
   at Rebus.SqlServer.DbConnectionProvider.<GetConnection>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.<EnsureTablesAreCreatedAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Rebus.SqlServer.AsyncHelpers.CustomSynchronizationContext.<<Run>b__7_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Rebus.SqlServer.AsyncHelpers.CustomSynchronizationContext.Run()
   at Rebus.SqlServer.AsyncHelpers.RunSync(Func`1 task)
   at Rebus.SqlServer.Sagas.SqlServerSagaStorage.EnsureTablesAreCreated()
   at Rebus.Config.SqlServerSagaConfigurationExtensions.<>c__DisplayClass0_0.<StoreInSqlServer>b__0(IResolutionContext c)
   at Rebus.Injection.Injectionist.Resolver`1.InvokeResolver(IResolutionContext context)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
```

And digging a little bit in the source code I see it uses System.Data.SqlClient so I understand the source of the exception but: is it possible to inject a connection factory and use Microsoft.Data.SqlClient?

**Comment by mookid8000** [comment]
OK, I'm an old dude, so please enlighten me: What's the difference between the two SQL drivers? (apart from the fact that System.Data.SqlClient apparently doesn't understand your connection string..... 😁 )

**Comment by gogux** [comment]
Well it's basically what you just pointed out 😅. My issue here is that System.Data.SqlCilent isn't able to manage encrypted tables/columns using the SQL Server feature AlwaysEncrypted (that's what the directive 'column encryption setting' in my connection string tries to enable). The most recent Microsoft.Data.SqlClient is capable of managing transparent encryption (at last) and also supports some of the newest features of SQL Server and Azure SQL. From now on in fact, MS will focus on Microsoft.Data.SqlClient to offer the latest features and they'll keep supporting System.Data.SqlClient but just as a legacy codebase.

Of course I could have a second connection string with the encryption disabled (excluding the offending directive) as the sagas persistence won't make any use of it, but seeing other projects (as Hangfire for example) I was wondering if there was also the option to inject custom connection factories to overcome this type of scenarios. I also wonder if it makes sense in this case 😊

**Comment by mookid8000** [comment]
I've released Rebus.SqlServer 7.0.0-a1, in which the dependency on System.Data.SqlClient has been replaced by Microsoft.Data.SqlClient.

Could you try and see if it solves your problem?

(PS: framework target has now been limited to .NET Standard 2.0)

**Comment by gogux** [comment]
I'll give it a try and let you know.

**Comment by gogux** [comment]
@mookid8000 I could finally test it with the affected customer project and it works perfect, thanks!

**Comment by mookid8000** [comment]
Good to hear 😁

**Comment by mookid8000** [comment]
It's out as Rebus.SqlServer 7.0.0 now 🙂
