### ISSUE TITLE
Question: How does sending messages work in regards to connection issues?

### ISSUE THREAD

**Issue by macchmie3** [rebus-org/Rebus.SqlServer#95]
Hi,

As a starter, I currently use Rebus in version 6.6.1 and Rebus.SqlServer in version 7.1.7. I am using Rebus with `UseSqlServerInLeaseMode`, and I use retries with `o.SimpleRetryStrategy(errorQueueAddress: "error-queue", maxDeliveryAttempts: 3);`

Now my question is around a following use case. Lets assume my "business case" is as follows:
1. Some process sends message of type MyMessageType1 processed by MyMessageType1Handler.
2. MyMessageType1Handler does some logic which includes sending another message of type MyMessageType2 processed by handler MyMessageType2Handler.

That means that MyMessageType1Handler has a following block of code:

```
public async  Task Handle(MyMessageType1 message)
    {
        try
        {
             Log.Info("Processing message MyMessageType1 ");

            /*
             * Some business logic here
            */

            await _bus.Send(new MyMessageType2
            {
                MyProp = "someValue"
            });
        }
        catch (Exception e)
        {
            Log.Error("Error occured!", e);
            throw new Exception(e.Message);
        }
    }

```

Now I see that I got a case when no error was logged in MyMessageType1Handler, so it's execution was successfull, no message landed in _error-queue_, there is also only 1 message _Processing message MyMessageType1_ logged, but there was a sql timeout while trying to save MyMessageType2 in input queue. Stack trace:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Rebus.SqlServer.Transport.SqlServerTransport.InnerSend(String destinationAddress, TransportMessage message, IDbConnection connection)
   at Rebus.SqlServer.Transport.SqlServerLeaseTransport.<>c__DisplayClass17_1.<<GetOutboundMessageBuffer>g__SendOutgoingMessages|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Rebus.Transport.TransactionContext.InvokeAsync(Func`2 actions)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)
ClientConnectionId:2feb293b-bc15-47fb-9dd9-3efe1a90e81c
Error Number:-2,State:0,Class:11
ClientConnectionId before routing:2e2746ef-ac68-4d1b-8216-46cd09a9c304
Routing Destination:<redacted for security reasons>
```

**Is it by design that a MyMessageType1 is "marked" as succesfully processed even though the handler didnt really complete the "send message" part. Is there a way to configure the handler to fail when MyMessageType2 cannot be saved into input queue?**

**Comment by mookid8000** [comment]
> Wouldn't it be better for the "delivered at least once" principle if the points 4 and 3 were reversed?

Doesn't it delete the message being handled and send all of the outgoing messages in the same SQL transaction?

**Comment by macchmie3** [comment]
I will provide trace from Profiler, but its different transaction for each of the 5 steps

**Comment by macchmie3** [comment]
@mookid8000 
Sorry for the late reply - I have created the trace. I would also like to correct myself - when I mentioned what steps are carried out during my scenario - I verified that steps 4 and 5 are done within 1 transaction (sending messages + inserting audit).

So to document it clearly:

Here is code for MyMessageHandler, which btw did not log any errors from this handler:
```
using System;
using System.Threading.Tasks;
using log4net;
using Rebus.Bus;
using Rebus.Handlers;
using Rebus.Retry.Simple;

namespace MyProject.RebusTest

public class MyMessageHandler : IHandleMessages<MyMessage>, IHandleMessages<IFailed<MyMessage>>
{
    private readonly IBus _bus;
    private static readonly ILog Log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

    public MyMessageHandler(IBus bus)
    {
        _bus = bus;
    }

    public async Task Handle(MyMessage message)
    {
        try
        {
            await _bus.Send(new SuccessfulMessage());
            await _bus.Send(new TriggerFailedMessage());
        }
        catch (Exception e)
        {
            Log.Error("MyMessageHandler Failed", e);
        }
    }
    
    public Task Handle(IFailed<MyMessage> message)
    {
        Log.Error($"IFailed<MyMessage> received");
        return Task.CompletedTask;
    }
}
```

Here is code for database trigger that I created to simulate connection error on sending 1 of the messages:
```
CREATE OR ALTER TRIGGER [dbo].[FailMessageTrigger] ON [dbo].[worker-input-queue]
AFTER INSERT
AS 
BEGIN

SET NOCOUNT ON;
DECLARE @Operation AS VARCHAR(32)
SET @Operation = NULL

IF EXISTS (SELECT 1 FROM inserted Where CONVERT(varchar(max), inserted.headers, 0) like '%TriggerFailedMessage%')
BEGIN
    WAITFOR DELAY '00:00:01'
    SELECT 1 / 0
END
END

```

Here is an unhandled exception that my app registered:

```
2022-08-02 11:39:05,228 [.NET ThreadPool Worker] WARN  ErrorTracking.InMemErrorTracker.Warn -- Unhandled exception 1 while handling message with ID "39fe5467-9a5c-4853-80df-9c30f40aad1e" Microsoft.Data.SqlClient.SqlException (0x80131904): Divide by zero error encountered.
The statement has been terminated.2022-08-02 11:39:05,228 [.NET ThreadPool Worker] WARN  ErrorTracking.InMemErrorTracker.Warn -- Unhandled exception 1 while handling message with ID "39fe5467-9a5c-4853-80df-9c30f40aad1e" Microsoft.Data.SqlClient.SqlException (0x80131904): Divide by zero error encountered.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Rebus.SqlServer.Transport.SqlServerTransport.InnerSend(String destinationAddress, TransportMessage message, IDbConnection connection)
   at Rebus.SqlServer.Transport.SqlServerLeaseTransport.<>c__DisplayClass17_1.<<GetOutboundMessageBuffer>g__SendOutgoingMessages|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Rebus.Transport.TransactionContext.InvokeAsync(Func`2 actions)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)
ClientConnectionId:5ee4c829-3e25-4d1c-90e3-645b14c001e2
Error Number:8134,State:1,Class:16
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Rebus.SqlServer.Transport.SqlServerTransport.InnerSend(String destinationAddress, TransportMessage message, IDbConnection connection)
   at Rebus.SqlServer.Transport.SqlServerLeaseTransport.<>c__DisplayClass17_1.<<GetOutboundMessageBuffer>g__SendOutgoingMessages|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Rebus.Transport.TransactionContext.InvokeAsync(Func`2 actions)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)
ClientConnectionId:5ee4c829-3e25-4d1c-90e3-645b14c001e2
Error Number:8134,State:1,Class:16

```

And last, but not least - here is SQL trace, which clearly shows that points 1, 2, 3 and 4 are all separate transactions.
![Sql profiler trace](https://user-images.githubusercontent.com/12615493/182366251-b4cbd0d1-a818-418a-9398-ae34ad1860a2.png)

As a side note - I am not sure why rebus is trying to perform unlock operation on message that is already deleted, might be a bug

**Comment by mookid8000** [comment]
I've added this test case where I replicated the problem: https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer.Tests/Bugs/TestDatabaseExceptionWhenSendingMessageUsingSqlTransport.cs

Turned out that the lease-based transport was using the wrong hook on Rebus' transaction context to complete the message. It shold be fixed in Rebus.SqlServer 7.3.0-b4, which is available on NuGet.org now. Could you try that and see how it behaves?

**Comment by macchmie3** [comment]
I have tested Rebus.SqlServer 7.3.0-b4 and I see (with profiler) that now points 3 and 4 from my case [(link to comment)](https://github.com/rebus-org/Rebus.SqlServer/issues/95#issuecomment-1184410364) are done in reverse order, which means - if sending of any of the messages failed within a handler, then that handler will also "fail" and it's message will be put in error queue / be retried. That would mean - case fixed! Also a small note, my tigger code which you partialy copied contained some overhead, which I - by mistake - didn't delete - you can remove following lines of unrelevant code from `FailMessageTrigger` from your linked file:

```
    DECLARE @Operation AS VARCHAR(32)
    SET @Operation = NULL
```
